export const placesData = [
  {
    id: 1,
    name: "Netarhat",
    image: "/Photos/PopularPlaces/Netarhat.jpg",
    rating: 4.8,
    reviews: 342,
    category: "Eco Tourism",
    description: "Popularly known as the Queen of Chotanagpur offering breathtaking sunrise views.",
  },
  {
    id: 2,
    name: "Betla National Park",
    image: "/Photos/PopularPlaces/Betla.jpg",
    rating: 4.7,
    reviews: 289,
    category: "Wildlife",
    description: "Home to elephants, tigers, and rich wildlife with pristine forest landscapes.",
  },
  {
    id: 3,
    name: "Parasnath Hill",
    image: "/Photos/PopularPlaces/Parasnath.jpg",
    rating: 4.9,
    reviews: 456,
    category: "Spiritual",
    description: "Sacred Jain pilgrimage site with temples atop Jharkhand's highest peak.",
  },
  {
    id: 4,
    name: "Baidyanath Dham",
    image: "/Photos/PopularPlaces/Baidyanath.jpg",
    rating: 4.9,
    reviews: 523,
    category: "Cultural",
    description: "One of the twelve Jyotirlingas, a major pilgrimage site in Deoghar.",
  },
  {
    id: 5,
    name: "Hundru Waterfall",
    image: "/Photos/PopularPlaces/Hundru.jpg",
    rating: 4.6,
    reviews: 310,
    category: "Nature",
    description: "Magnificent waterfall formed on Subarnarekha River surrounded by forests.",
  },
  {
    id: 6,
    name: "Dassam Falls",
    image: "/Photos/PopularPlaces/Dassam.jpg",
    rating: 4.7,
    reviews: 275,
    category: "Nature",
    description: "Majestic waterfall known for its scenic beauty and refreshing atmosphere.",
  },
  {
    id: 7,
    name: "Jonha Falls",
    image: "/Photos/PopularPlaces/Jonha.jpg",
    rating: 4.5,
    reviews: 198,
    category: "Adventure",
    description: "Known as Gautamdhara, surrounded by lush forests and tall cliffs.",
  },
  {
    id: 8,
    name: "McCluskieganj",
    image: "/Photos/PopularPlaces/McCluskieganj.jpg",
    rating: 4.4,
    reviews: 150,
    category: "Heritage",
    description: "Famous for its Anglo-Indian heritage, colonial bungalows, and calm surroundings.",
  },
  {
    id: 9,
    name: "Patratu Valley",
    image: "/Photos/PopularPlaces/Patratu.jpg",
    rating: 4.8,
    reviews: 480,
    category: "Scenic",
    description: "Beautiful valley with Serpentine roads, lakes, and misty hills.",
  },
  {
    id: 10,
    name: "Hazaribagh Lake",
    image: "/Photos/PopularPlaces/HazaribaghLake.jpg",
    rating: 4.3,
    reviews: 210,
    category: "Relaxation",
    description: "Calm lakeside view perfect for boating and peaceful family visits.",
  },
];
