// src/data/eventsData.js

export const eventsData = [
  {
    id: 1,
    title: "Sohrai Art Festival – Hazaribagh",
    categoryKey: "Cultural",
    label: "Cultural Festivals",
    dateRange: "Nov 20–25, 2025 • 6 Days",
    startDay: 20, // calendar highlight
    location: "Hazaribagh District",
    priceLabel: "₹100",
    isFree: false,
    badge: "₹100",
    tag: "Featured",
    image:
      "https://images.unsplash.com/photo-1601807873928-3c3c5476644a?auto=format&w=900",
    shortDescription:
      "Experience the vibrant Sohrai tribal art tradition with local artists.",
    isFeatured: true,
    isThisWeek: false,
  },
  {
    id: 2,
    title: "Chhau Dance Festival",
    categoryKey: "Tribal",
    label: "Tribal Dance & Art",
    dateRange: "Dec 10–14, 2025 • 5 Days",
    startDay: 10,
    location: "Seraikela, Jharkhand",
    priceLabel: "₹150",
    isFree: false,
    badge: "₹150",
    tag: "Featured",
    image:
      "https://images.unsplash.com/photo-1520781359717-3eb98461c9fe?auto=format&w=900",
    shortDescription:
      "Witness the spectacular masked Chhau dance recognized by UNESCO.",
    isFeatured: true,
    isThisWeek: false,
  },
  {
    id: 3,
    title: "Karma Festival Celebration",
    categoryKey: "Seasonal",
    label: "Seasonal Events",
    dateRange: "Aug 15–17, 2025 • 3 Days",
    startDay: 15,
    location: "Multiple Villages, Ranchi",
    priceLabel: "Free Entry",
    isFree: true,
    badge: "Free",
    tag: "Featured",
    image:
      "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&w=900",
    shortDescription:
      "Celebrate the harvest festival with traditional Karma dance around sacred trees.",
    isFeatured: true,
    isThisWeek: true,
  },
  {
    id: 4,
    title: "Sarhul Spring Festival",
    categoryKey: "Religious",
    label: "Religious Events",
    dateRange: "March 20–22, 2025 • 3 Days",
    startDay: 21,
    location: "Rural Villages, Ranchi",
    priceLabel: "Free Entry",
    isFree: true,
    badge: "Free",
    tag: "Featured",
    image:
      "https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&w=900",
    shortDescription:
      "Spring worship festival celebrating nature, Sal trees and village deities.",
    isFeatured: true,
    isThisWeek: false,
  },
  {
    id: 5,
    title: "Sarhul Spring Festival – Hazaribagh",
    categoryKey: "Seasonal",
    label: "Seasonal Events",
    dateRange: "March 20–22, 2025 • 3 Days",
    startDay: 22,
    location: "Hazaribagh, Jharkhand",
    priceLabel: "Free Entry",
    isFree: true,
    badge: "Free",
    image:
      "https://images.unsplash.com/photo-1520781359717-3eb98461c9fe?auto=format&w=900",
    shortDescription:
      "Welcome spring with tree worship and traditional rituals.",
    isFeatured: false,
    isThisWeek: false,
  },
  {
    id: 6,
    title: "Tribal Music & Drums Festival",
    categoryKey: "Music",
    label: "Music & Performances",
    dateRange: "Jan 5–7, 2025 • 3 Days",
    startDay: 5,
    location: "Jamshedpur Convention Center",
    priceLabel: "₹250",
    isFree: false,
    badge: "₹250",
    image:
      "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&w=900",
    shortDescription:
      "Immerse in rhythms of indigenous drums, songs and performances.",
    isFeatured: false,
    isThisWeek: false,
  },
  {
    id: 7,
    title: "Chaibasa Haat – Local Fair",
    categoryKey: "Fairs",
    label: "Local Fairs",
    dateRange: "Every Saturday • Weekly",
    startDay: 8,
    location: "Chaibasa Market Ground",
    priceLabel: "Free Entry",
    isFree: true,
    badge: "Free",
    image:
      "https://images.unsplash.com/photo-1502581827181-9cf3c3ee0106?auto=format&w=900",
    shortDescription:
      "Colorful weekly market with crafts, food and local performances.",
    isFeatured: false,
    isThisWeek: true,
  },
  {
    id: 8,
    title: "Jharkhand Food & Culture Festival",
    categoryKey: "Food",
    label: "Food Festivals",
    dateRange: "Feb 14–16, 2025 • 3 Days",
    startDay: 14,
    location: "Morabadi Ground, Ranchi",
    priceLabel: "₹50",
    isFree: false,
    badge: "₹50",
    image:
      "https://images.unsplash.com/photo-1514516430032-7d9a7a86c9a2?auto=format&w=900",
    shortDescription:
      "Taste traditional cuisine and enjoy cultural performances in one festival.",
    isFeatured: false,
    isThisWeek: false,
  },
  {
    id: 9,
    title: "Tribal Art & Craft Exhibition",
    categoryKey: "Workshops",
    label: "Workshops & Exhibitions",
    dateRange: "Oct 1–10, 2025 • 10 Days",
    startDay: 2,
    location: "State Museum, Ranchi",
    priceLabel: "₹100",
    isFree: false,
    badge: "₹100",
    image:
      "https://images.unsplash.com/photo-1598387864449-bafb2a595b05?auto=format&w=900",
    shortDescription:
      "Explore and purchase authentic tribal crafts and artworks.",
    isFeatured: false,
    isThisWeek: false,
  },
];
